# -*- coding: utf-8 -*-
"""REGRESION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgBNP58xsiulLmG3FVe9r6wa6m5G-Dw_
"""

# Commented out IPython magic to ensure Python compatibility.
# utilizado para manejos de directorios y rutas
import pandas as pd
import os

# Computacion vectorial y cientifica para python
import numpy as np

# Librerias para graficación (trazado de gráficos)
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D  # Necesario para graficar superficies 3D

# llama a matplotlib a embeber graficas dentro de los cuadernillos
# %matplotlib inline

# from google.colab import drive
# drive.mount("/content/gdrive")

# 2.1 Normalización de caracteristicas

# Cargar datos desde tu ruta específica (Asegúrate de que la carpeta sea la correcta)
# NOTA: Proporciona el archivo cars.csv en esta carpeta o cambia la ruta
ruta = 'cars.csv'  # Cambia a la ruta correcta donde esté tu archivo CSV

df = pd.read_csv(ruta)

# TRUCO: Solo nos quedamos con columnas numéricas y booleanas, y quitamos filas vacías
df = df.select_dtypes(include=['int64', 'float64', 'bool']).dropna()

# Extraemos y (precio) y X (todo lo demás convertido a decimales)
y = df['price_usd'].values
X = df.drop('price_usd', axis=1).values.astype(float)

m = y.size
print("Cantidad de datos (m):", m)
print("Cantidad de características:", X.shape[1])

# imprimir algunos puntos de datos
print('{:>8s}{:>8s}{:>10s}'.format('X[:,0]', 'X[:, 1]', 'y'))
print('-'*26)
for i in range(10):
    print('{:8.0f}{:8.0f}{:10.2f}'.format(X[i, 0], X[i, 1], y[i]))

def featureNormalize(X):

    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)

    # Previene error si alguna desviación estándar es 0
    sigma[sigma == 0] = 1

    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

# llama featureNormalize con los datos cargados
X_norm, mu, sigma = featureNormalize(X)

print('Datos normalizados:')
print(X_norm[:3, :]) # Mostramos solo las primeras 3 filas para no saturar la pantalla
print('Media calculada:', mu)
print('Desviación estandar calculada:', sigma)

# Añade el termino de interseccion a X
# (Columna de unos para X0)
X = np.concatenate([np.ones((m, 1)), X_norm], axis=1)
print("X con la columna de unos:")
print(X[:3, :])

### 2.2 Descenso por el gradiente

def computeCostMulti(X, y, theta):
    # Inicializa algunos valores utiles
    m = y.shape[0] # numero de ejemplos de entrenamiento

    J = 0
    J = (1/(2 * m)) * np.sum(np.square(np.dot(X, theta) - y))

    return J

def gradientDescentMulti(X, y, theta, alpha, num_iters):
    # Inicializa algunos valores
    m = y.shape[0] # numero de ejemplos de entrenamiento

    # realiza una copia de theta, el cual será acutalizada por el descenso por el gradiente
    theta = theta.copy()
    J_history = []

    for i in range(num_iters):
        theta = theta - (alpha / m) * (np.dot(X, theta) - y).dot(X)
        J_history.append(computeCostMulti(X, y, theta))

    return theta, J_history

# Elegir algun valor para alpha (probar varias alternativas)
alpha = 0.01 # Se sube un poco a 0.01 para converger mejor
num_iters = 10000

# inicializa theta y ejecuta el descenso por el gradiente
# CAMBIO: Usamos 20 porque tenemos 19 características + la intersección (1)
theta = np.zeros(20)
theta, J_history = gradientDescentMulti(X, y, theta, alpha, num_iters)

# Grafica la convergencia del costo
pyplot.plot(np.arange(len(J_history)), J_history, lw=2)
pyplot.xlabel('Numero de iteraciones')
pyplot.ylabel('Costo J')

# Muestra los resultados del descenso por el gradiente
print('theta calculado por el descenso por el gradiente: {:s}'.format(str(theta)))

# Estimar el precio para un nuevo registro de prueba (un auto específico)
# CAMBIO: Agregamos 20 valores (El '1' inicial + 19 valores de características del auto)
X_array = [1, 190000.0, 2010.0, 0.0, 2.5, 0.0, 0.0, 9.0, 13.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 16.0]

# Normalizamos usando los índices del 1 al 20
X_array[1:20] = (X_array[1:20] - mu) / sigma
price = np.dot(X_array, theta)

print('El precio predecido (usando el descenso por el gradiente): ${:.2f} USD'.format(price))